[project]
name = "lsp-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
    "lsprotocol>=2023.0.1",
    "mcp>=1.6.0",
    "pydantic>=2.11.3",
]

[project.scripts]
lsp-mcp-server = "lsp:main"
